<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (c) 2026, RTE (http://www.rte-france.com)
  ~ This Source Code Form is subject to the terms of the Mozilla Public
  ~ License, v. 2.0. If a copy of the MPL was not distributed with this
  ~ file, You can obtain one at http://mozilla.org/MPL/2.0/.
  -->

<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.farao-community.farao</groupId>
        <artifactId>farao-parent-ws</artifactId>
        <version>1.14.0</version>
    </parent>

    <artifactId>ce-merging-server</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>ce-merging-server</name>
    <description>Server application for the CE merging process.</description>
    <url>https://github.com/farao-community/ce-merging-server</url>

    <scm>
        <connection>scm:git:https://github.com/farao-community/ce-merging-server.git</connection>
        <developerConnection>scm:git:https://github.com/farao-community/ce-merging-server.git</developerConnection>
        <url>https://github.com/farao-community/ce-merging-server.git</url>
    </scm>

    <properties>
        <sonar.exclusions>**/resources/**</sonar.exclusions>
        <org.mapstruct.version>1.6.3</org.mapstruct.version>
        <powsybl.core.version>7.1.1</powsybl.core.version>
        <powsybl.entsoe.version>3.1.0</powsybl.entsoe.version>
        <powsybl.open-loadflow.version>2.1.1</powsybl.open-loadflow.version>
        <powsybl.open-rao.version>7.1.3</powsybl.open-rao.version>
        <assertj-core.version>3.26.3</assertj-core.version>
        <springdoc-openapi.version>2.8.17</springdoc-openapi.version>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>jaxb2-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>bci</id>
                        <goals>
                            <goal>xjc</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>src/main/resources/xsd/bci</source>
                            </sources>
                            <arguments>
                                <argument>-XautoNameResolution</argument>
                            </arguments>
                            <packageName>com.farao_community.farao.ce_merging.xsd.bci</packageName>
                        </configuration>
                    </execution>
                    <execution>
                        <id>xnodes</id>
                        <goals>
                            <goal>xjc</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>src/main/resources/xsd/xnodes</source>
                            </sources>
                            <packageName>com.farao_community.farao.ce_merging.xsd.xnodes</packageName>
                            <outputDirectory>${project.build.directory}/generated-sources/jaxb/xnodes</outputDirectory>
                        </configuration>
                    </execution>
                    <execution>
                        <id>forecast_netpositions</id>
                        <goals>
                            <goal>xjc</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>src/main/resources/xsd/forecast_netpositions</source>
                            </sources>
                            <packageName>com.farao_community.farao.ce_merging.xsd.forecast_netpositions</packageName>
                            <outputDirectory>${project.build.directory}/generated-sources/jaxb/forecast_netpositions</outputDirectory>
                        </configuration>
                    </execution>
                    <execution>
                        <id>glsk_fix</id>
                        <goals>
                            <goal>xjc</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>src/main/resources/xsd/glsk_fix</source>
                            </sources>
                            <packageName>com.farao_community.farao.ce_merging.xsd.glsk_fix</packageName>
                            <outputDirectory>${project.build.directory}/generated-sources/jaxb/glsk_fix</outputDirectory>
                        </configuration>
                    </execution>
                    <execution>
                        <id>xlog</id>
                        <goals>
                            <goal>xjc</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>src/main/resources/xsd/final_cgm_result/exec-logs.xsd</source>
                            </sources>
                            <packageName>com.farao_community.farao.ce_merging.xsd.execution_logs</packageName>
                            <outputDirectory>${project.build.directory}/generated-sources/jaxb/exec_logs</outputDirectory>
                        </configuration>
                    </execution>
                    <execution>
                        <id>merging_logs</id>
                        <goals>
                            <goal>xjc</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>src/main/resources/xsd/merging_logs/merging_logs.xsd</source>
                            </sources>
                            <packageName>com.farao_community.farao.ce_merging.xsd.merging_logs</packageName>
                            <outputDirectory>${project.build.directory}/generated-sources/jaxb/merging_logs</outputDirectory>
                        </configuration>
                    </execution>
                    <execution>
                        <id>refprog</id>
                        <goals>
                            <goal>xjc</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>src/main/resources/xsd/refprog/refprog.xsd</source>
                            </sources>
                            <packageName>com.farao_community.farao.ce_merging.xsd.ref_prog</packageName>
                            <outputDirectory>${project.build.directory}/generated-sources/jaxb/ref_prog</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>${org.mapstruct.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <classpathDependencyExcludes>
                        <classpathDependencyExclude>com.powsybl:powsybl-config-classic</classpathDependencyExclude>
                    </classpathDependencyExcludes>
                </configuration>
            </plugin>
        </plugins>
    </build>
    <dependencies>
        <!-- COMPILE DEPENDENCIES -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.xml.bind</groupId>
            <artifactId>jakarta.xml.bind-api</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.persistence</groupId>
            <artifactId>jakarta.persistence-api</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-tracing-bridge-brave</artifactId>
        </dependency>
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
            <version>${org.mapstruct.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>${springdoc-openapi.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
        <dependency>
            <groupId>com.powsybl</groupId>
            <artifactId>powsybl-iidm-api</artifactId>
            <version>${powsybl.core.version}</version>
        </dependency>
        <dependency>
            <groupId>com.powsybl</groupId>
            <artifactId>powsybl-loadflow-api</artifactId>
            <version>${powsybl.core.version}</version>
        </dependency>
        <dependency>
            <groupId>com.powsybl</groupId>
            <artifactId>powsybl-contingency-api</artifactId>
            <version>${powsybl.core.version}</version>
        </dependency>
        <dependency>
            <groupId>com.powsybl</groupId>
            <artifactId>powsybl-ucte-converter</artifactId>
            <version>${powsybl.core.version}</version>
        </dependency>
        <dependency>
            <groupId>com.powsybl</groupId>
            <artifactId>powsybl-ucte-network</artifactId>
            <version>${powsybl.core.version}</version>
        </dependency>
        <dependency>
            <groupId>com.powsybl</groupId>
            <artifactId>powsybl-commons</artifactId>
            <version>${powsybl.core.version}</version>
        </dependency>
        <dependency>
            <groupId>com.powsybl</groupId>
            <artifactId>powsybl-glsk-document-io-api</artifactId>
            <version>${powsybl.entsoe.version}</version>
        </dependency>
        <dependency>
            <groupId>com.powsybl</groupId>
            <artifactId>powsybl-glsk-quality-check-ucte</artifactId>
            <version>${powsybl.entsoe.version}</version>
        </dependency>
        <dependency>
            <groupId>com.powsybl</groupId>
            <artifactId>powsybl-balances-adjustment</artifactId>
            <version>${powsybl.entsoe.version}</version>
        </dependency>
        <dependency>
            <groupId>com.powsybl</groupId>
            <artifactId>open-rao-virtual-hubs-xml</artifactId>
            <version>${powsybl.open-rao.version}</version>
        </dependency>
        <dependency>
            <groupId>com.powsybl</groupId>
            <artifactId>open-rao-virtual-hubs-json</artifactId>
            <version>${powsybl.open-rao.version}</version>
        </dependency>

        <!-- RUNTIME DEPENDENCIES -->
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jaxb</groupId>
            <artifactId>jaxb-runtime</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>com.powsybl</groupId>
            <artifactId>powsybl-config-classic</artifactId>
            <version>${powsybl.core.version}</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>com.powsybl</groupId>
            <artifactId>powsybl-ampl-converter</artifactId>
            <version>${powsybl.core.version}</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>com.powsybl</groupId>
            <artifactId>powsybl-cgmes-conversion</artifactId>
            <version>${powsybl.core.version}</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>com.powsybl</groupId>
            <artifactId>powsybl-iidm-impl</artifactId>
            <version>${powsybl.core.version}</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>com.powsybl</groupId>
            <artifactId>powsybl-iidm-scripting</artifactId>
            <version>${powsybl.core.version}</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>com.powsybl</groupId>
            <artifactId>powsybl-iidm-serde</artifactId>
            <version>${powsybl.core.version}</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>com.powsybl</groupId>
            <artifactId>powsybl-glsk-document-ucte</artifactId>
            <version>${powsybl.entsoe.version}</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>com.powsybl</groupId>
            <artifactId>powsybl-open-loadflow</artifactId>
            <version>${powsybl.open-loadflow.version}</version>
        </dependency>

        <!-- TEST DEPENDENCIES -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>${assertj-core.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
        </dependency>
    </dependencies>
</project>